use std::{
    collections::{BTreeMap, BTreeSet},
    ffi::{OsStr, OsString},
    fs,
    io::{self, Read},
    path::{Path, PathBuf},
    process::{Command, ExitStatus, Stdio},
    str::FromStr,
    sync::{
        atomic::{AtomicBool, AtomicU64, Ordering},
        Arc,
    },
    thread,
    time::{Duration, Instant},
};

use parc::contract::{
    Architecture, CompilerFamily, CompilerIdentity, ContentFingerprint, OperatingSystem,
    SourceFingerprint, TargetSpec,
};

use crate::contract::{
    AbiProbeEvidence, AbiProbeEvidenceInput, ArtifactFingerprint, LincCode, ProbeCompilerArgument,
    ProbeEnvironmentEntry, ProbeEnvironmentIdentity, ProbeEnvironmentPolicy, ProbeEnvironmentValue,
    ProbeExecutionPolicy, ProbeMethod, ProbeProcessResult, ProbeProcessStatus, ProbeResourceLimits,
    ProbeRunnerArgument, ProbeRunnerEvidence, ProbeSubject, ProbeSubjectOutcome,
    ProbeSubjectStatus,
};

use super::error::{io_error, NativeError, NativeResult};

const MARKER_PREFIX: &str = "LINC_PROBE_V1|";
const MAX_PROBE_SOURCE_BYTES: usize = 8 * 1024 * 1024;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EnvironmentSetting {
    Set { name: String, value: OsString },
    Unset { name: String },
}

impl EnvironmentSetting {
    fn name(&self) -> &str {
        match self {
            Self::Set { name, .. } | Self::Unset { name } => name,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RunnerSpec {
    program: PathBuf,
    arguments: Vec<ProbeRunnerArgument>,
}

impl RunnerSpec {
    pub fn new(program: PathBuf, arguments: Vec<ProbeRunnerArgument>) -> NativeResult<Self> {
        if !program.is_absolute() {
            return Err(NativeError::InvalidRunner {
                detail: "runner program must be an absolute path".to_owned(),
            });
        }
        if arguments
            .iter()
            .filter(|argument| matches!(argument, ProbeRunnerArgument::ProbeExecutable))
            .count()
            != 1
        {
            return Err(NativeError::InvalidRunner {
                detail: "runner requires exactly one probe-executable placeholder".to_owned(),
            });
        }
        if arguments.iter().any(|argument| {
            matches!(argument, ProbeRunnerArgument::Literal(value) if os_units(value).contains(&0))
        }) {
            return Err(NativeError::InvalidRunner {
                detail: "runner arguments cannot contain NUL".to_owned(),
            });
        }
        Ok(Self { program, arguments })
    }

    pub fn program(&self) -> &Path {
        &self.program
    }

    pub fn arguments(&self) -> &[ProbeRunnerArgument] {
        &self.arguments
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProbeExpectation {
    subject: ProbeSubject,
    evidence_fingerprint: ContentFingerprint,
}

impl ProbeExpectation {
    pub const fn new(subject: ProbeSubject, evidence_fingerprint: ContentFingerprint) -> Self {
        Self {
            subject,
            evidence_fingerprint,
        }
    }

    pub const fn subject(&self) -> ProbeSubject {
        self.subject
    }

    pub const fn evidence_fingerprint(&self) -> ContentFingerprint {
        self.evidence_fingerprint
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProbeProgram {
    includes: Vec<String>,
    body: String,
}

impl ProbeProgram {
    pub fn try_new(includes: Vec<String>, body: String) -> NativeResult<Self> {
        if body.is_empty() || body.contains('\0') || body.len() > MAX_PROBE_SOURCE_BYTES {
            return Err(NativeError::InvalidPolicy {
                detail: "probe body is empty, contains NUL, or exceeds the source limit".to_owned(),
            });
        }
        let mut seen = BTreeSet::new();
        for include in &includes {
            if !valid_include(include) || !seen.insert(include) {
                return Err(NativeError::InvalidPolicy {
                    detail: format!("probe include {include:?} is unsafe or duplicated"),
                });
            }
        }
        Ok(Self { includes, body })
    }

    pub fn includes(&self) -> &[String] {
        &self.includes
    }

    pub fn body(&self) -> &str {
        &self.body
    }

    fn render(&self, expectations: &[ProbeExpectation]) -> String {
        let mut source = String::from("/* generated by linc probe protocol v1 */\n");
        for include in &self.includes {
            source.push_str("#include <");
            source.push_str(include);
            source.push_str(">\n");
        }
        source.push_str("enum {\n");
        for (index, expectation) in expectations.iter().enumerate() {
            source.push_str("  linc_probe_subject_");
            source.push_str(&index.to_string());
            source.push_str(" = ");
            source.push_str(&index.to_string());
            source.push_str(", /* ");
            source.push_str(&expectation.subject().declaration().to_string());
            source.push_str(" */\n");
        }
        source.push_str("};\n");
        source.push_str(&self.body);
        if !self.body.ends_with('\n') {
            source.push('\n');
        }
        source
    }
}

pub struct ProbeRequest<'a> {
    pub source_fingerprint: SourceFingerprint,
    pub target: &'a TargetSpec,
    pub program: ProbeProgram,
    pub expectations: Vec<ProbeExpectation>,
    pub method: ProbeMethod,
    pub compiler_executable: PathBuf,
    pub compiler_arguments: Vec<ProbeCompilerArgument>,
    pub environment: Vec<EnvironmentSetting>,
    pub temporary_parent: PathBuf,
    pub resource_limits: ProbeResourceLimits,
    pub runner: Option<RunnerSpec>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProbeRejectionKind {
    Timeout,
    OutputLimit,
    Nonzero,
    ParserGap,
    MissingRunner,
    InvalidRunner,
    CompilerIdentity,
    UnsafeStreams,
}

#[derive(Debug)]
pub struct ProbeRejection {
    kind: ProbeRejectionKind,
    code: LincCode,
    message: String,
    process: Option<ProbeProcessResult>,
}

impl ProbeRejection {
    pub const fn kind(&self) -> ProbeRejectionKind {
        self.kind
    }

    pub fn code(&self) -> &LincCode {
        &self.code
    }

    pub fn message(&self) -> &str {
        &self.message
    }

    pub const fn process(&self) -> Option<&ProbeProcessResult> {
        self.process.as_ref()
    }
}

#[derive(Debug)]
// Keeping evidence inline makes the successful public result straightforward
// to destructure; probe executions are infrequent and never stored in arrays.
#[allow(clippy::large_enum_variant)]
pub enum ProbeRunOutcome {
    Verified {
        evidence: AbiProbeEvidence,
        compiler_sysroot: PathBuf,
    },
    Rejected(ProbeRejection),
}

impl ProbeRunOutcome {
    pub fn evidence(&self) -> Option<&AbiProbeEvidence> {
        match self {
            Self::Verified { evidence, .. } => Some(evidence),
            Self::Rejected(_) => None,
        }
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct ProbeRunner;

impl ProbeRunner {
    pub fn run(&self, mut request: ProbeRequest<'_>) -> NativeResult<ProbeRunOutcome> {
        canonicalize_expectations(&mut request.expectations)?;
        validate_compiler_arguments(&request.compiler_arguments)?;
        if !request.compiler_executable.is_absolute() {
            return Err(NativeError::InvalidPolicy {
                detail: "probe compiler executable must be an absolute path".to_owned(),
            });
        }
        if !request.temporary_parent.is_absolute() {
            return Err(NativeError::InvalidPolicy {
                detail: "probe temporary parent must be an absolute path".to_owned(),
            });
        }
        if request.method == ProbeMethod::ExecutedHarness && request.runner.is_none() {
            let foreign = is_foreign_target(request.target);
            return Ok(ProbeRunOutcome::Rejected(rejection(
                if foreign {
                    ProbeRejectionKind::MissingRunner
                } else {
                    ProbeRejectionKind::InvalidRunner
                },
                if foreign { "LINC-E3034" } else { "LINC-E3035" },
                if foreign {
                    format!(
                        "foreign target {} cannot execute without an explicit runner",
                        request.target.triple()
                    )
                } else {
                    "executed probes require an explicit runner command".to_owned()
                },
                None,
            )?));
        }
        let compiler = fs::canonicalize(&request.compiler_executable).map_err(|error| {
            io_error(
                "canonicalize probe compiler",
                &request.compiler_executable,
                error,
            )
        })?;
        if !compiler.is_file() {
            return Err(NativeError::ToolIdentity {
                path: compiler,
                detail: "compiler is not a regular file".to_owned(),
            });
        }
        let environment = checked_environment(&request.environment)?;
        let environment_identity = environment_identity(&request.environment)?;
        let execution_policy = ProbeExecutionPolicy::try_new(
            fs::canonicalize(&request.temporary_parent).map_err(|error| {
                io_error(
                    "canonicalize probe temporary parent",
                    &request.temporary_parent,
                    error,
                )
            })?,
            environment_identity,
            request.resource_limits,
        )?;
        let identity = match identify_compiler(&compiler, &environment, request.resource_limits) {
            Ok(identity) => identity,
            Err(error) => {
                return Ok(ProbeRunOutcome::Rejected(rejection(
                    ProbeRejectionKind::CompilerIdentity,
                    "LINC-E3036",
                    error.to_string(),
                    None,
                )?));
            }
        };
        if identity.compiler.reported_target() != request.target.triple() {
            return Ok(ProbeRunOutcome::Rejected(rejection(
                ProbeRejectionKind::CompilerIdentity,
                "LINC-E3036",
                format!(
                    "compiler reports target {}, request requires {}",
                    identity.compiler.reported_target(),
                    request.target.triple()
                ),
                None,
            )?));
        }

        let source = request.program.render(&request.expectations);
        if source.len() > MAX_PROBE_SOURCE_BYTES {
            return Err(NativeError::InvalidPolicy {
                detail: format!(
                    "rendered probe source exceeds the {MAX_PROBE_SOURCE_BYTES}-byte limit"
                ),
            });
        }
        let source_fingerprint = ContentFingerprint::from_content(source.as_bytes());
        let temporary = tempfile::Builder::new()
            .prefix("linc-probe-")
            .tempdir_in(execution_policy.temporary_parent())
            .map_err(|error| {
                io_error(
                    "create secure probe directory",
                    execution_policy.temporary_parent(),
                    error,
                )
            })?;
        let source_path = temporary.path().join("probe.c");
        let output_path = temporary.path().join("probe.out");
        fs::write(&source_path, source.as_bytes())
            .map_err(|error| io_error("write probe source", &source_path, error))?;

        let compiler_args =
            materialize_compiler_arguments(&request.compiler_arguments, &source_path, &output_path);
        let mut command = Command::new(&compiler);
        command.args(&compiler_args);
        apply_environment(&mut command, &environment);
        let compile_capture = match run_bounded(
            command,
            execution_policy.limits().wall_time_millis(),
            execution_policy.limits().max_output_bytes(),
        ) {
            Ok(capture) => capture,
            Err(ProcessLimit::Timeout) => {
                return Ok(ProbeRunOutcome::Rejected(rejection(
                    ProbeRejectionKind::Timeout,
                    "LINC-E3030",
                    format!(
                        "compiler exceeded {} ms",
                        execution_policy.limits().wall_time_millis()
                    ),
                    None,
                )?));
            }
            Err(ProcessLimit::Output) => {
                return Ok(ProbeRunOutcome::Rejected(rejection(
                    ProbeRejectionKind::OutputLimit,
                    "LINC-E3031",
                    format!(
                        "compiler exceeded {} output bytes",
                        execution_policy.limits().max_output_bytes()
                    ),
                    None,
                )?));
            }
            Err(ProcessLimit::UnsafeStreams) => {
                return Ok(ProbeRunOutcome::Rejected(rejection(
                    ProbeRejectionKind::UnsafeStreams,
                    "LINC-E3037",
                    "compiler descendants retained inherited output streams".to_owned(),
                    None,
                )?));
            }
            Err(ProcessLimit::Io(error)) => {
                return Err(io_error("run probe compiler", &compiler, error));
            }
        };
        let output_artifact = if output_path.is_file() {
            Some(ArtifactFingerprint::from_content(&read_bounded_file(
                &output_path,
                execution_policy.limits().max_memory_bytes(),
                "read probe output",
            )?))
        } else {
            None
        };
        let compile_result = process_result(&compile_capture, output_artifact);
        if !compile_result.succeeded() || output_artifact.is_none() {
            return Ok(ProbeRunOutcome::Rejected(rejection(
                ProbeRejectionKind::Nonzero,
                "LINC-E3032",
                status_label(compile_capture.status),
                Some(compile_result),
            )?));
        }

        let (runner_evidence, execution_result, marker_bytes) = match request.method {
            ProbeMethod::ExecutedHarness => {
                let runner = request
                    .runner
                    .expect("executed probe runner was checked before compiler invocation");
                let runner_path = fs::canonicalize(runner.program()).map_err(|error| {
                    io_error("canonicalize probe runner", runner.program(), error)
                })?;
                if !runner_path.is_file() {
                    return Ok(ProbeRunOutcome::Rejected(rejection(
                        ProbeRejectionKind::InvalidRunner,
                        "LINC-E3035",
                        "runner is not a regular file".to_owned(),
                        None,
                    )?));
                }
                let runner_bytes = read_bounded_file(
                    &runner_path,
                    execution_policy.limits().max_memory_bytes(),
                    "read probe runner",
                )?;
                let runner_fingerprint = ArtifactFingerprint::from_content(&runner_bytes);
                let runner_args = materialize_runner_arguments(runner.arguments(), &output_path);
                let mut command = Command::new(&runner_path);
                command.args(&runner_args);
                apply_environment(&mut command, &environment);
                let capture = match run_bounded(
                    command,
                    execution_policy.limits().wall_time_millis(),
                    execution_policy.limits().max_output_bytes(),
                ) {
                    Ok(capture) => capture,
                    Err(ProcessLimit::Timeout) => {
                        return Ok(ProbeRunOutcome::Rejected(rejection(
                            ProbeRejectionKind::Timeout,
                            "LINC-E3030",
                            "probe runner timed out".to_owned(),
                            None,
                        )?));
                    }
                    Err(ProcessLimit::Output) => {
                        return Ok(ProbeRunOutcome::Rejected(rejection(
                            ProbeRejectionKind::OutputLimit,
                            "LINC-E3031",
                            "probe runner exceeded the output limit".to_owned(),
                            None,
                        )?));
                    }
                    Err(ProcessLimit::UnsafeStreams) => {
                        return Ok(ProbeRunOutcome::Rejected(rejection(
                            ProbeRejectionKind::UnsafeStreams,
                            "LINC-E3037",
                            "runner descendants retained inherited output streams".to_owned(),
                            None,
                        )?));
                    }
                    Err(ProcessLimit::Io(error)) => {
                        return Err(io_error("run probe runner", &runner_path, error));
                    }
                };
                let result = process_result(&capture, None);
                if !result.succeeded() {
                    return Ok(ProbeRunOutcome::Rejected(rejection(
                        ProbeRejectionKind::Nonzero,
                        "LINC-E3032",
                        status_label(capture.status),
                        Some(result),
                    )?));
                }
                (
                    ProbeRunnerEvidence::Executed {
                        executable_path: runner_path,
                        executable_fingerprint: runner_fingerprint,
                        arguments: runner.arguments,
                    },
                    Some(result),
                    capture.stdout,
                )
            }
            ProbeMethod::CompilerLayoutDump => {
                if request.runner.is_some() {
                    return Err(NativeError::InvalidRunner {
                        detail: "compile-only probe method cannot carry a runner".to_owned(),
                    });
                }
                let mut output = compile_capture.stdout.clone();
                output.extend_from_slice(&compile_capture.stderr);
                (ProbeRunnerEvidence::NotExecuted, None, output)
            }
            ProbeMethod::CompileTimeAssertion => {
                if request.runner.is_some() {
                    return Err(NativeError::InvalidRunner {
                        detail: "compile-time assertion cannot carry a runner".to_owned(),
                    });
                }
                (ProbeRunnerEvidence::NotExecuted, None, Vec::new())
            }
        };
        let outcomes = match request.method {
            ProbeMethod::CompileTimeAssertion => request
                .expectations
                .iter()
                .map(|expected| {
                    ProbeSubjectOutcome::try_new(
                        expected.subject,
                        ProbeSubjectStatus::Verified {
                            evidence_fingerprint: expected.evidence_fingerprint,
                        },
                    )
                })
                .collect::<Result<Vec<_>, _>>()?,
            ProbeMethod::CompilerLayoutDump | ProbeMethod::ExecutedHarness => {
                match parse_markers(&marker_bytes, &request.expectations) {
                    Ok(outcomes) => outcomes,
                    Err(error) => {
                        return Ok(ProbeRunOutcome::Rejected(rejection(
                            ProbeRejectionKind::ParserGap,
                            "LINC-E3033",
                            error.to_string(),
                            execution_result,
                        )?));
                    }
                }
            }
        };
        let evidence = AbiProbeEvidence::try_new(AbiProbeEvidenceInput {
            source_fingerprint: request.source_fingerprint,
            target_fingerprint: request.target.fingerprint(),
            compiler: identity.compiler,
            compiler_executable: compiler,
            compiler_arguments: request.compiler_arguments,
            abi_flags: request.target.abi_flags().to_vec(),
            probe_source_fingerprint: source_fingerprint,
            subjects: request
                .expectations
                .iter()
                .map(ProbeExpectation::subject)
                .collect(),
            method: request.method,
            execution_policy,
            compile_result,
            runner: runner_evidence,
            execution_result,
            subject_outcomes: outcomes,
        })?;
        Ok(ProbeRunOutcome::Verified {
            evidence,
            compiler_sysroot: identity.sysroot,
        })
    }
}

#[derive(Debug)]
struct CompilerObservation {
    compiler: CompilerIdentity,
    sysroot: PathBuf,
}

fn identify_compiler(
    compiler: &Path,
    environment: &[(String, Option<OsString>)],
    limits: ProbeResourceLimits,
) -> NativeResult<CompilerObservation> {
    let executable = read_bounded_file(
        compiler,
        limits.max_memory_bytes(),
        "read compiler executable",
    )?;
    let version = run_identity_command(compiler, ["--version"], environment, limits)?;
    let target = run_identity_command(compiler, ["-dumpmachine"], environment, limits)?;
    let sysroot = run_identity_command(compiler, ["-print-sysroot"], environment, limits)?;
    let version_text = text_output(&version, "compiler version")?;
    let reported_target = text_output(&target, "compiler target")?;
    let sysroot_text = text_output(&sysroot, "compiler sysroot")?;
    let first_line = version_text
        .lines()
        .next()
        .filter(|line| !line.trim().is_empty())
        .ok_or_else(|| NativeError::ToolIdentity {
            path: compiler.to_path_buf(),
            detail: "compiler version output is empty".to_owned(),
        })?;
    let lower = first_line.to_ascii_lowercase();
    let family = if lower.contains("apple clang") {
        CompilerFamily::AppleClang
    } else if lower.contains("clang") {
        CompilerFamily::Clang
    } else if lower.contains("gcc") || lower.contains("gnu") {
        CompilerFamily::Gcc
    } else {
        return Err(NativeError::ToolIdentity {
            path: compiler.to_path_buf(),
            detail: format!("unrecognized compiler family in {first_line:?}"),
        });
    };
    let logical_name = compiler
        .file_name()
        .and_then(OsStr::to_str)
        .unwrap_or("compiler");
    let compiler_identity = CompilerIdentity::try_new(
        family,
        format!("toolchain/bin/{logical_name}"),
        ContentFingerprint::from_content(&executable),
        ContentFingerprint::from_content(&version.stdout),
        reported_target.trim(),
        first_line.trim(),
    )
    .map_err(|error| NativeError::ToolIdentity {
        path: compiler.to_path_buf(),
        detail: error.to_string(),
    })?;
    let sysroot = if sysroot_text.trim().is_empty() {
        PathBuf::from("/")
    } else {
        fs::canonicalize(sysroot_text.trim()).map_err(|error| {
            io_error(
                "canonicalize compiler sysroot",
                Path::new(sysroot_text.trim()),
                error,
            )
        })?
    };
    Ok(CompilerObservation {
        compiler: compiler_identity,
        sysroot,
    })
}

fn run_identity_command<const N: usize>(
    compiler: &Path,
    arguments: [&str; N],
    environment: &[(String, Option<OsString>)],
    limits: ProbeResourceLimits,
) -> NativeResult<ProcessCapture> {
    let mut command = Command::new(compiler);
    command.args(arguments);
    apply_environment(&mut command, environment);
    match run_bounded(
        command,
        limits.wall_time_millis(),
        limits.max_output_bytes(),
    ) {
        Ok(capture) if capture.status.success() => Ok(capture),
        Ok(capture) => Err(NativeError::ToolIdentity {
            path: compiler.to_path_buf(),
            detail: status_label(capture.status),
        }),
        Err(ProcessLimit::Timeout) => Err(NativeError::ProbeTimeout {
            millis: limits.wall_time_millis(),
        }),
        Err(ProcessLimit::Output) => Err(NativeError::ProbeOutputLimit {
            limit: limits.max_output_bytes(),
        }),
        Err(ProcessLimit::UnsafeStreams) => Err(NativeError::ProbeUnsafeStreams),
        Err(ProcessLimit::Io(error)) => Err(io_error("query compiler identity", compiler, error)),
    }
}

fn text_output<'a>(capture: &'a ProcessCapture, field: &str) -> NativeResult<&'a str> {
    std::str::from_utf8(&capture.stdout).map_err(|_| NativeError::ToolIdentity {
        path: PathBuf::from("<compiler>"),
        detail: format!("{field} output is not UTF-8"),
    })
}

fn read_bounded_file(path: &Path, limit: u64, operation: &'static str) -> NativeResult<Vec<u8>> {
    let file = fs::File::open(path).map_err(|error| io_error(operation, path, error))?;
    let metadata = file
        .metadata()
        .map_err(|error| io_error("stat bounded probe file", path, error))?;
    if !metadata.is_file() {
        return Err(NativeError::ToolIdentity {
            path: path.to_path_buf(),
            detail: "bounded probe input is not a regular file".to_owned(),
        });
    }
    if metadata.len() > limit {
        return Err(NativeError::ArtifactTooLarge {
            path: path.to_path_buf(),
            limit,
        });
    }
    let mut bytes =
        Vec::with_capacity(usize::try_from(metadata.len().min(limit)).unwrap_or(1024 * 1024));
    file.take(limit.saturating_add(1))
        .read_to_end(&mut bytes)
        .map_err(|error| io_error(operation, path, error))?;
    if u64::try_from(bytes.len()).unwrap_or(u64::MAX) > limit {
        return Err(NativeError::ArtifactTooLarge {
            path: path.to_path_buf(),
            limit,
        });
    }
    if u64::try_from(bytes.len()).unwrap_or(u64::MAX) != metadata.len() {
        return Err(NativeError::ToolIdentity {
            path: path.to_path_buf(),
            detail: "bounded probe file changed while it was read".to_owned(),
        });
    }
    Ok(bytes)
}

fn checked_environment(
    settings: &[EnvironmentSetting],
) -> NativeResult<Vec<(String, Option<OsString>)>> {
    let mut names = BTreeSet::new();
    let mut checked = Vec::with_capacity(settings.len());
    for setting in settings {
        let name = setting.name();
        if name.is_empty()
            || name.contains('=')
            || name.bytes().any(|byte| byte == 0 || !byte.is_ascii())
            || !names.insert(name.to_owned())
        {
            return Err(NativeError::InvalidPolicy {
                detail: format!("invalid or duplicate environment variable {name:?}"),
            });
        }
        match setting {
            EnvironmentSetting::Set { name, value } => {
                if os_units(value).contains(&0) {
                    return Err(NativeError::InvalidPolicy {
                        detail: format!("environment value for {name} contains NUL"),
                    });
                }
                checked.push((name.clone(), Some(value.clone())));
            }
            EnvironmentSetting::Unset { name } => checked.push((name.clone(), None)),
        }
    }
    Ok(checked)
}

fn environment_identity(settings: &[EnvironmentSetting]) -> NativeResult<ProbeEnvironmentIdentity> {
    if settings.is_empty() {
        return Ok(ProbeEnvironmentIdentity::try_new(
            ProbeEnvironmentPolicy::Empty,
            Vec::new(),
        )?);
    }
    let entries = settings
        .iter()
        .map(|setting| match setting {
            EnvironmentSetting::Set { name, value } => ProbeEnvironmentEntry::try_new(
                name.clone(),
                ProbeEnvironmentValue::Set {
                    value_fingerprint: ContentFingerprint::from_content(&os_units(value)),
                },
            ),
            EnvironmentSetting::Unset { name } => {
                ProbeEnvironmentEntry::try_new(name.clone(), ProbeEnvironmentValue::Unset)
            }
        })
        .collect::<Result<Vec<_>, _>>()?;
    Ok(ProbeEnvironmentIdentity::try_new(
        ProbeEnvironmentPolicy::Explicit,
        entries,
    )?)
}

fn apply_environment(command: &mut Command, environment: &[(String, Option<OsString>)]) {
    command.env_clear();
    for (name, value) in environment {
        if let Some(value) = value {
            command.env(name, value);
        } else {
            command.env_remove(name);
        }
    }
    command.stdin(Stdio::null());
}

fn validate_compiler_arguments(arguments: &[ProbeCompilerArgument]) -> NativeResult<()> {
    let sources = arguments
        .iter()
        .filter(|argument| matches!(argument, ProbeCompilerArgument::ProbeSource))
        .count();
    let outputs = arguments
        .iter()
        .filter(|argument| matches!(argument, ProbeCompilerArgument::OutputArtifact))
        .count();
    if sources != 1 || outputs != 1 {
        return Err(NativeError::InvalidPolicy {
            detail: "compiler argv requires exactly one source and output placeholder".to_owned(),
        });
    }
    if arguments.iter().any(|argument| {
        matches!(argument, ProbeCompilerArgument::Literal(value) if os_units(value).contains(&0))
    }) {
        return Err(NativeError::InvalidPolicy {
            detail: "compiler arguments cannot contain NUL".to_owned(),
        });
    }
    Ok(())
}

fn materialize_compiler_arguments(
    arguments: &[ProbeCompilerArgument],
    source: &Path,
    output: &Path,
) -> Vec<OsString> {
    arguments
        .iter()
        .map(|argument| match argument {
            ProbeCompilerArgument::Literal(value) => value.clone(),
            ProbeCompilerArgument::ProbeSource => source.as_os_str().to_os_string(),
            ProbeCompilerArgument::OutputArtifact => output.as_os_str().to_os_string(),
        })
        .collect()
}

fn materialize_runner_arguments(
    arguments: &[ProbeRunnerArgument],
    executable: &Path,
) -> Vec<OsString> {
    arguments
        .iter()
        .map(|argument| match argument {
            ProbeRunnerArgument::Literal(value) => value.clone(),
            ProbeRunnerArgument::ProbeExecutable => executable.as_os_str().to_os_string(),
        })
        .collect()
}

fn canonicalize_expectations(expectations: &mut [ProbeExpectation]) -> NativeResult<()> {
    if expectations.is_empty() {
        return Err(NativeError::InvalidPolicy {
            detail: "probe requires at least one subject".to_owned(),
        });
    }
    expectations.sort_by_key(ProbeExpectation::subject);
    if expectations
        .windows(2)
        .any(|pair| pair[0].subject == pair[1].subject)
    {
        return Err(NativeError::InvalidPolicy {
            detail: "probe subjects must be unique".to_owned(),
        });
    }
    Ok(())
}

fn parse_markers(
    output: &[u8],
    expectations: &[ProbeExpectation],
) -> NativeResult<Vec<ProbeSubjectOutcome>> {
    let output = std::str::from_utf8(output).map_err(|_| NativeError::ProbeParserGap {
        detail: "probe marker stream is not UTF-8".to_owned(),
    })?;
    let expected = expectations
        .iter()
        .map(|expectation| (subject_key(expectation.subject), expectation))
        .collect::<BTreeMap<_, _>>();
    let mut observed = BTreeMap::new();
    for line in output.lines() {
        let Some(marker) = line.strip_prefix(MARKER_PREFIX) else {
            continue;
        };
        let mut parts = marker.split('|');
        let kind = parts.next();
        let declaration = parts.next();
        let fingerprint = parts.next();
        if parts.next().is_some()
            || kind.is_none()
            || declaration.is_none()
            || fingerprint.is_none()
        {
            return Err(NativeError::ProbeParserGap {
                detail: format!("malformed marker line {line:?}"),
            });
        }
        let key = format!("{}:{}", kind.unwrap(), declaration.unwrap());
        let expected = expected
            .get(&key)
            .ok_or_else(|| NativeError::ProbeParserGap {
                detail: format!("marker refers to unexpected subject {key}"),
            })?;
        let fingerprint = ContentFingerprint::from_str(fingerprint.unwrap()).map_err(|error| {
            NativeError::ProbeParserGap {
                detail: format!("invalid marker fingerprint: {error}"),
            }
        })?;
        if fingerprint != expected.evidence_fingerprint {
            return Err(NativeError::ProbeParserGap {
                detail: format!("marker fingerprint differs for {key}"),
            });
        }
        if observed.insert(key.clone(), fingerprint).is_some() {
            return Err(NativeError::ProbeParserGap {
                detail: format!("duplicate marker for {key}"),
            });
        }
    }
    if observed.len() != expected.len() {
        return Err(NativeError::ProbeParserGap {
            detail: format!(
                "observed {} subject markers, expected {}",
                observed.len(),
                expected.len()
            ),
        });
    }
    expectations
        .iter()
        .map(|expectation| {
            ProbeSubjectOutcome::try_new(
                expectation.subject,
                ProbeSubjectStatus::Verified {
                    evidence_fingerprint: expectation.evidence_fingerprint,
                },
            )
            .map_err(NativeError::from)
        })
        .collect()
}

fn subject_key(subject: ProbeSubject) -> String {
    let kind = match subject {
        ProbeSubject::RecordLayout { .. } => "record_layout",
        ProbeSubject::EnumRepresentation { .. } => "enum_representation",
        ProbeSubject::CallableAbi { .. } => "callable_abi",
    };
    format!("{kind}:{}", subject.declaration())
}

fn valid_include(include: &str) -> bool {
    !include.is_empty()
        && include.len() <= 4096
        && !include.starts_with('/')
        && !include.contains('\\')
        && include
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'.' | b'/' | b'-'))
        && include
            .split('/')
            .all(|component| !component.is_empty() && !matches!(component, "." | ".."))
}

fn is_foreign_target(target: &TargetSpec) -> bool {
    target.architecture() != host_architecture()
        || target.operating_system() != host_operating_system()
}

fn host_architecture() -> Architecture {
    match std::env::consts::ARCH {
        "x86" => Architecture::X86,
        "x86_64" => Architecture::X86_64,
        "arm" => Architecture::Arm,
        "aarch64" => Architecture::Aarch64,
        "riscv32" => Architecture::RiscV32,
        "riscv64" => Architecture::RiscV64,
        "powerpc" => Architecture::PowerPc,
        "powerpc64" => Architecture::PowerPc64,
        "s390x" => Architecture::S390x,
        "mips" => Architecture::Mips,
        "mips64" => Architecture::Mips64,
        "sparc64" => Architecture::Sparc64,
        "wasm32" => Architecture::Wasm32,
        "wasm64" => Architecture::Wasm64,
        _ => Architecture::Wasm32,
    }
}

fn host_operating_system() -> OperatingSystem {
    match std::env::consts::OS {
        "linux" => OperatingSystem::Linux,
        "android" => OperatingSystem::Android,
        "macos" => OperatingSystem::MacOs,
        "ios" => OperatingSystem::Ios,
        "windows" => OperatingSystem::Windows,
        "freebsd" => OperatingSystem::FreeBsd,
        "netbsd" => OperatingSystem::NetBsd,
        "openbsd" => OperatingSystem::OpenBsd,
        "dragonfly" => OperatingSystem::DragonFly,
        _ => OperatingSystem::None,
    }
}

#[derive(Debug)]
struct ProcessCapture {
    status: ExitStatus,
    stdout: Vec<u8>,
    stderr: Vec<u8>,
}

#[derive(Debug)]
enum ProcessLimit {
    Timeout,
    Output,
    UnsafeStreams,
    Io(io::Error),
}

fn run_bounded(
    mut command: Command,
    wall_time_millis: u64,
    max_output_bytes: u64,
) -> Result<ProcessCapture, ProcessLimit> {
    configure_process_group(&mut command).map_err(ProcessLimit::Io)?;
    command.stdout(Stdio::piped()).stderr(Stdio::piped());
    let mut child = command.spawn().map_err(ProcessLimit::Io)?;
    let stdout = child
        .stdout
        .take()
        .ok_or_else(|| ProcessLimit::Io(io::Error::other("child stdout was not captured")))?;
    let stderr = child
        .stderr
        .take()
        .ok_or_else(|| ProcessLimit::Io(io::Error::other("child stderr was not captured")))?;
    let total = Arc::new(AtomicU64::new(0));
    let exceeded = Arc::new(AtomicBool::new(false));
    let stdout_thread = spawn_reader(
        stdout,
        Arc::clone(&total),
        Arc::clone(&exceeded),
        max_output_bytes,
    );
    let stderr_thread = spawn_reader(
        stderr,
        Arc::clone(&total),
        Arc::clone(&exceeded),
        max_output_bytes,
    );
    let start = Instant::now();
    let mut limit = None;
    let status = loop {
        if exceeded.load(Ordering::Acquire) {
            limit = Some(ProcessLimit::Output);
            terminate_process_group(&mut child);
            break reap_child_bounded(&mut child, Duration::from_millis(100))
                .map_err(ProcessLimit::Io)?;
        }
        if start.elapsed() >= Duration::from_millis(wall_time_millis) {
            limit = Some(ProcessLimit::Timeout);
            terminate_process_group(&mut child);
            break reap_child_bounded(&mut child, Duration::from_millis(100))
                .map_err(ProcessLimit::Io)?;
        }
        match child.try_wait().map_err(ProcessLimit::Io)? {
            Some(status) => break Some(status),
            None => thread::sleep(Duration::from_millis(2)),
        }
    };

    let close_deadline = Instant::now() + Duration::from_millis(50);
    while (!stdout_thread.is_finished() || !stderr_thread.is_finished())
        && Instant::now() < close_deadline
    {
        thread::sleep(Duration::from_millis(1));
    }
    let forced_stream_cleanup = !stdout_thread.is_finished() || !stderr_thread.is_finished();
    if forced_stream_cleanup {
        terminate_process_group(&mut child);
        let cleanup_deadline = Instant::now() + Duration::from_millis(100);
        while (!stdout_thread.is_finished() || !stderr_thread.is_finished())
            && Instant::now() < cleanup_deadline
        {
            thread::sleep(Duration::from_millis(1));
        }
    }
    let readers_closed = stdout_thread.is_finished() && stderr_thread.is_finished();
    if !readers_closed {
        // Dropping a JoinHandle detaches it. The dedicated process group has
        // already been terminated, so an inherited pipe cannot block this
        // bounded API even if the host cannot reap a hostile descendant.
        drop(stdout_thread);
        drop(stderr_thread);
        return Err(limit.unwrap_or(ProcessLimit::UnsafeStreams));
    }

    if let Some(limit) = limit {
        let _ = stdout_thread.join();
        let _ = stderr_thread.join();
        return Err(limit);
    }
    if forced_stream_cleanup {
        let _ = stdout_thread.join();
        let _ = stderr_thread.join();
        return Err(ProcessLimit::UnsafeStreams);
    }
    let stdout = stdout_thread
        .join()
        .map_err(|_| ProcessLimit::Io(io::Error::other("stdout reader panicked")))?
        .map_err(ProcessLimit::Io)?;
    let stderr = stderr_thread
        .join()
        .map_err(|_| ProcessLimit::Io(io::Error::other("stderr reader panicked")))?
        .map_err(ProcessLimit::Io)?;
    if exceeded.load(Ordering::Acquire) {
        return Err(ProcessLimit::Output);
    }
    let status = status.ok_or_else(|| {
        ProcessLimit::Io(io::Error::other(
            "probe child could not be reaped within the cleanup deadline",
        ))
    })?;
    Ok(ProcessCapture {
        status,
        stdout,
        stderr,
    })
}

fn spawn_reader<R: Read + Send + 'static>(
    mut reader: R,
    total: Arc<AtomicU64>,
    exceeded: Arc<AtomicBool>,
    max_output_bytes: u64,
) -> thread::JoinHandle<io::Result<Vec<u8>>> {
    thread::spawn(move || {
        let capacity = usize::try_from(max_output_bytes.min(64 * 1024)).unwrap_or(64 * 1024);
        let mut kept = Vec::with_capacity(capacity);
        let mut buffer = [0_u8; 8192];
        loop {
            let count = reader.read(&mut buffer)?;
            if count == 0 {
                break;
            }
            let count_u64 = u64::try_from(count).unwrap_or(u64::MAX);
            let previous = total.fetch_add(count_u64, Ordering::AcqRel);
            if previous.saturating_add(count_u64) > max_output_bytes {
                exceeded.store(true, Ordering::Release);
                break;
            }
            kept.extend_from_slice(&buffer[..count]);
        }
        Ok(kept)
    })
}

#[cfg(unix)]
fn configure_process_group(command: &mut Command) -> io::Result<()> {
    use std::os::unix::process::CommandExt as _;
    command.process_group(0);
    Ok(())
}

#[cfg(not(unix))]
fn configure_process_group(_command: &mut Command) -> io::Result<()> {
    Err(io::Error::new(
        io::ErrorKind::Unsupported,
        "bounded probe process groups are certified only on Unix hosts",
    ))
}

fn terminate_process_group(child: &mut std::process::Child) {
    #[cfg(unix)]
    {
        let group = format!("-{}", child.id());
        let mut killer = Command::new("/bin/kill");
        killer
            .args(["-KILL", "--", group.as_str()])
            .env_clear()
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null());
        if let Ok(mut process) = killer.spawn() {
            let _ = reap_child_bounded(&mut process, Duration::from_millis(50));
        }
    }
    let _ = child.kill();
}

fn reap_child_bounded(
    child: &mut std::process::Child,
    timeout: Duration,
) -> io::Result<Option<ExitStatus>> {
    let deadline = Instant::now() + timeout;
    loop {
        if let Some(status) = child.try_wait()? {
            return Ok(Some(status));
        }
        if Instant::now() >= deadline {
            return Ok(None);
        }
        thread::sleep(Duration::from_millis(1));
    }
}

fn process_result(
    capture: &ProcessCapture,
    output_artifact: Option<ArtifactFingerprint>,
) -> ProbeProcessResult {
    ProbeProcessResult::new(
        process_status(capture.status),
        ContentFingerprint::from_content(&capture.stdout),
        ContentFingerprint::from_content(&capture.stderr),
        output_artifact,
    )
}

fn process_status(status: ExitStatus) -> ProbeProcessStatus {
    if let Some(code) = status.code() {
        ProbeProcessStatus::Exited { code }
    } else {
        ProbeProcessStatus::Signaled {
            signal: exit_signal(status).unwrap_or(-1),
        }
    }
}

#[cfg(unix)]
fn exit_signal(status: ExitStatus) -> Option<i32> {
    use std::os::unix::process::ExitStatusExt as _;
    status.signal()
}

#[cfg(not(unix))]
fn exit_signal(_status: ExitStatus) -> Option<i32> {
    None
}

fn status_label(status: ExitStatus) -> String {
    match process_status(status) {
        ProbeProcessStatus::Exited { code } => format!("exit code {code}"),
        ProbeProcessStatus::Signaled { signal } => format!("signal {signal}"),
    }
}

fn rejection(
    kind: ProbeRejectionKind,
    code: &str,
    message: String,
    process: Option<ProbeProcessResult>,
) -> NativeResult<ProbeRejection> {
    Ok(ProbeRejection {
        kind,
        code: LincCode::try_new(code)?,
        message,
        process,
    })
}

#[cfg(unix)]
fn os_units(value: &OsStr) -> Vec<u8> {
    use std::os::unix::ffi::OsStrExt as _;
    value.as_bytes().to_vec()
}

#[cfg(windows)]
fn os_units(value: &OsStr) -> Vec<u8> {
    use std::os::windows::ffi::OsStrExt as _;
    value.encode_wide().flat_map(u16::to_le_bytes).collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::contract::DeclarationId;

    #[test]
    fn include_validation_rejects_traversal_and_shell_spelling() {
        assert!(valid_include("stdint.h"));
        assert!(valid_include("sys/types.h"));
        assert!(!valid_include("../secret.h"));
        assert!(!valid_include("x.h;touch"));
        assert!(!valid_include("/absolute.h"));
    }

    #[test]
    fn marker_parser_requires_exact_subject_count_and_fingerprint() {
        let declaration = DeclarationId::from_str(
            "pdecl1_524bcccd395cfaad5d0697f01bc545663e82eaad03be1e515beeb81933f5b37d",
        )
        .unwrap();
        let fingerprint = ContentFingerprint::from_content(b"evidence");
        let expected = [ProbeExpectation::new(
            ProbeSubject::CallableAbi { declaration },
            fingerprint,
        )];
        let marker = format!("{MARKER_PREFIX}callable_abi|{declaration}|{fingerprint}\n");
        assert_eq!(
            parse_markers(marker.as_bytes(), &expected).unwrap().len(),
            1
        );
        assert!(parse_markers(b"", &expected).is_err());
    }
}
